name: 3dhoi
channels:
  - bottler
  - iopath
  - fvcore
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.3.1
  - numpy-base=1.21.2
  - pip=21.2.4
  - python=3.8.10
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytorch=1.10.1
  - pytorch-mutex=1.0
  - torchaudio=0.10.1
  - torchvision=0.11.2
  - tqdm=4.62.3
  - pip:
    - imageio==2.14.1
    - json5==0.9.6
    - matplotlib==3.5.1
    - natsort==8.1.0
    - numpy==1.22.1
    - open3d==0.14.1
    - opencv-python==4.4.0.46
    - pillow==9.0.0
    - pyrender==0.1.45
    - scikit-image==0.19.1
    - scikit-learn==1.0.2
    - scipy==1.7.3
